src/Entity/Video.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\VideoRepository")
 */
class Video
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $link;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\CategoriaVideo", inversedBy="videos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categoria;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Image",cascade={"persist"})
     */
    private $imagen;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titulo;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $duracion;

    /**
     * @ORM\Column(type="date")
     */
    private $fecha;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $id_vimeo;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $es_gratis;

    /**
     * @ORM\Column(type="integer")
     */
    private $orden;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $visible;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $id_preview_vimeo;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $resumen;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $destacado;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aws_url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $aws_preview_url;

    public function __construct()
    {
        $this->updated_at = new \DateTime();
    }

    public function __toString()
    {
        return $this->getTitulo();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(string $link): self
    {
        $this->link = $link;

        return $this;
    }



    public function getCategoria(): ?CategoriaVideo
    {
        return $this->categoria;
    }

    public function setCategoria(?CategoriaVideo $categoria): self
    {
        $this->categoria = $categoria;

        return $this;
    }

    public function getImagen(): ?Image
    {
        return $this->imagen;
    }

    public function setImagen(?Image $imagen): self
    {
        $this->imagen = $imagen;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDuracion(): ?string
    {
        return $this->duracion;
    }

    public function setDuracion(string $duracion): self
    {
        $this->duracion = $duracion;

        return $this;
    }

    public function getFecha(): ?\DateTimeInterface
    {
        return $this->fecha;
    }

    public function setFecha(\DateTimeInterface $fecha): self
    {
        $this->fecha = $fecha;

        return $this;
    }

    public function getIdVimeo(): ?string
    {
        return $this->id_vimeo;
    }

    public function setIdVimeo(string $id_vimeo): self
    {
        $this->id_vimeo = $id_vimeo;

        return $this;
    }

    public function getEsGratis(): ?bool
    {
        return $this->es_gratis;
    }

    public function setEsGratis(?bool $es_gratis): self
    {
        $this->es_gratis = $es_gratis;

        return $this;
    }

    public function getOrden(): ?int
    {
        return $this->orden;
    }

    public function setOrden(int $orden): self
    {
        $this->orden = $orden;

        return $this;
    }

    public function getVisible(): ?bool
    {
        return $this->visible;
    }

    public function setVisible(?bool $visible): self
    {
        $this->visible = $visible;

        return $this;
    }

    public function getTags(): ?string
    {
        return $this->tags;
    }

    public function setTags(?string $tags): self
    {
        $this->tags = $tags;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIdPreviewVimeo(): ?string
    {
        return $this->id_preview_vimeo;
    }

    public function setIdPreviewVimeo(?string $id_preview_vimeo): self
    {
        $this->id_preview_vimeo = $id_preview_vimeo;

        return $this;
    }

    public function getResumen(): ?string
    {
        return $this->resumen;
    }

    public function setResumen(?string $resumen): self
    {
        $this->resumen = $resumen;

        return $this;
    }

    public function getDestacado(): ?bool
    {
        return $this->destacado;
    }

    public function setDestacado(?bool $destacado): self
    {
        $this->destacado = $destacado;

        return $this;
    }

    public function getAwsUrl(): ?string
    {
        return $this->aws_url;
    }

    public function setAwsUrl(?string $aws_url): self
    {
        $this->aws_url = $aws_url;

        return $this;
    }

    public function getAwsPreviewUrl(): ?string
    {
        return $this->aws_preview_url;
    }

    public function setAwsPreviewUrl(?string $aws_preview_url): self
    {
        $this->aws_preview_url = $aws_preview_url;

        return $this;
    }
}

templates/basic/home.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>TO do</h1>





{% endblock %}
{% block javascripts %}
    <script>

    </script>
{% endblock %}

templates/basic/mail.html.twig
<table style="width: 600px; max-width: 100%; background-color: #0A1723; border: 4px solid #E5B464; margin: 0 auto;">
    <tr>
        <th style="text-align: center; padding: 2rem 2rem 0 2rem;" colspan="2">
            <a href="http://thejpchannel.com/" target="_blank" style="display: inline-block; vertical-align: top;"><img style="width: 150px;display: inline-block; vertical-align: top;" src="{{ asset('images/logo-h.png') }}"/></a><br>
            <h2 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.5rem; font-family:Courier New, Georgia, Times, Times New Roman;">El canal más top de Colombia</h2>
        </th>
    </tr>
    <tr>
        <td style="padding: 0 2rem; text-align: center" colspan="2">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.8rem; font-size: 1rem; font-family: Verdana, Geneva, Tahoma, sans-serif;">
                Wuon, felicitaciones por haberte suscrito al canal más top de Internet. Pagando haces que mi empresa pueda seguir siendo play, ayudas a los pobres que necesitan techo y comida; y lo más importante: dejas de ser de esos mantecos que lo quieren todo gratis.
            </p>
        </td>
    </tr>
    <tr>
        <td style="text-align: center" colspan="2">
            <h3 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif;"><strong>{{ qi.texto('cheers_mk') }}</strong></h3>
        </td>
    </tr>
    <tr>
        <td style="padding: 2rem 0.5rem 2rem 2rem;">
            <a style="display: inline-block; vertical-align: top;" href="https://www.techo.org/colombia/?gclid=EAIaIQobChMI4vu_1-276AIV8IFaBR3RdQFcEAAYASAAEgLl-fD_BwE" target="_blank"><img width="100" src="{{ asset('images/logo_techo.jpg') }}"/></a>
        </td>
        <td style="padding: 2rem 2rem 2rem 0.5rem;">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.5rem; font-size: 1rem; font-style: italic; font-family: Verdana, Geneva, Tahoma, sans-serif;">"Gracias a tu aporte hemos logrado entregar un kit de alimentación más a una familia que se ve afectada por esta situación de emergencia."</p>
        </td>
    </tr>
    <tr>
        <td style="padding: 2rem; text-align: center;" colspan="2">
            <a style="display: inline-block; vertical-align: top; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif; vertical-align: top; color: #E5B464;" href="http://thejpchannel.com/" target="_blank">thejpchannel.com/</a>
        </td>
    </tr>
</table>

/*old*/

<table style="width: 600px; max-width: 100%; background-color: #0A1723; border: 4px solid #E5B464; margin: 0 auto;">
    <tbody>
    <tr>
        <th colspan="2" style="text-align: center; padding: 2rem 2rem 0 2rem;"><a href="http://thejpchannel.com/" style="display: inline-block; vertical-align: top;" target="_blank"><img src="https://test.thejpchannel.com/images/logo-h.png" style="width: 150px;display: inline-block; vertical-align: top;" /></a>
            <h2 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.5rem; font-family:Courier New, Georgia, Times, Times New Roman;">El canal m&aacute;s top de Colombia</h2>
        </th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 0 2rem; text-align: center">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.8rem; font-size: 1rem; font-family: Verdana, Geneva, Tahoma, sans-serif;">Wuon, felicitaciones por haberte suscrito al canal m&aacute;s top de Internet. Pagando haces que mi empresa pueda seguir siendo play, ayudas a los pobres que necesitan techo y comida; y lo m&aacute;s importante: dejas de ser de esos mantecos que lo quieren todo gratis.</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="text-align: center">
            <h3 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif;"><strong>&iexcl;Cheers, mk! Welcome to my world...</strong></h3>
        </td>
    </tr>
    <tr>
        <td style="padding: 2rem 0.5rem 2rem 2rem;"><a href="https://www.techo.org/colombia/?gclid=EAIaIQobChMI4vu_1-276AIV8IFaBR3RdQFcEAAYASAAEgLl-fD_BwE" style="display: inline-block; vertical-align: top;" target="_blank"><img src="https://test.thejpchannel.com/images/logo_techo.jpg" width="100" /></a></td>
        <td style="padding: 2rem 2rem 2rem 0.5rem;">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.5rem; font-size: 1rem; font-style: italic; font-family: Verdana, Geneva, Tahoma, sans-serif;">&quot;Gracias a tu aporte hemos logrado entregar un kit de alimentaci&oacute;n m&aacute;s a una familia que se ve afectada por esta situaci&oacute;n de emergencia.&quot;</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding: 2rem; text-align: center;"><a href="http://thejpchannel.com/" style="display: inline-block; vertical-align: top; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif; vertical-align: top; color: #E5B464;" target="_blank">thejpchannel.com/</a></td>
    </tr>
    </tbody>
</table>



<table style="width: 600px; max-width: 100%; background-color: #0A1723; border: 4px solid #E5B464; margin: 0 auto;">
    <tbody>
    <tr>
        <th colspan="2" style="text-align: center; padding: 2rem 2rem 0 2rem;">
            <a href="http://thejpchannel.com/" style="display: inline-block; vertical-align: top;" target="_blank">
                <img src="https://test.thejpchannel.com/images/logo-h.png" style="width: 100px;display: inline-block; vertical-align: top;" />
            </a><br>
            <h2 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.5rem; font-family:Courier New, Georgia, Times, Times New Roman;">El canal m&aacute;s top de Colombia</h2>
        </th>
    </tr>
    <tr>
        <td colspan="2" style="padding: 0 2rem; text-align: center">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.8rem; font-size: 1rem; font-family: Verdana, Geneva, Tahoma, sans-serif;">Wuon, felicitaciones por haberte suscrito al canal m&aacute;s top de Internet. Pagando haces que mi empresa pueda seguir siendo play, ayudas a los pobres que necesitan techo y comida; y lo m&aacute;s importante: dejas de ser de esos mantecos que lo quieren todo gratis.</p>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="text-align: center">
            <h3 style="display: inline-block; vertical-align: top; color: #E5B464; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif;"><strong>&iexcl;Cheers, mk! Welcome to my world...</strong></h3>
        </td>
    </tr>
    <tr>
        <td style="text-align: center;">
            <img style="display: inline-block; vertical-align: top; width: 150px;" src="{{ asset('images/logo_techo.jpg') }}">
        </td>
    </tr>
    <tr>
        <td style="padding: 2rem; text-align: center;">
            <p style="display: inline-block; vertical-align: top; color: white; line-height: 1.5rem; font-size: 1rem; font-style: italic; font-family: Verdana, Geneva, Tahoma, sans-serif;">&quot;Gracias a tu aporte hemos logrado entregar un kit de alimentaci&oacute;n m&aacute;s a una familia que se ve afectada por esta situaci&oacute;n de emergencia.&quot;</p>
        </td>
    </tr>
    <tr>
        <td style="text-align: center; padding: 2rem 0;">
            <img style="display: inline-block; vertical-align:top;" width="400" src="{{ asset('images/gracias.png') }}"/>
        </td>
    </tr>
    <tr>
        <td style="padding: 1rem 2rem; background-color: white; text-align: center;">
            <!--<a style="margin: 0 5px; display: inline-block; vertical-align: middle;" href="https://www.techo.org/colombia/?gclid=EAIaIQobChMI4vu_1-276AIV8IFaBR3RdQFcEAAYASAAEgLl-fD_BwE" target="_blank"><img src="https://test.thejpchannel.com/images/logo-techo.png" width="150" /></a>-->
            <a style="margin: 0 10px; display: inline-block; vertical-align: middle;" href="https://www.techo.org/colombia/?gclid=EAIaIQobChMI4vu_1-276AIV8IFaBR3RdQFcEAAYASAAEgLl-fD_BwE" target="_blank"><img src="https://test.thejpchannel.com/images/logo-techo.png" width="150" /></a>
            <a style="margin: 0 10px; display: inline-block; vertical-align: middle;" target="_blank"><img width="150" src="https://test.thejpchannel.com/images/riano-producciones.jpg"/></a>
            <a style="margin: 0 10px; display: inline-block; vertical-align: middle;" href="http://iridian.co/" target="_blank"><img width="120" src="https://test.thejpchannel.com/images/iridian-color.png"></a>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="padding: 2rem; text-align: center;"><a href="http://thejpchannel.com" style="display: inline-block; vertical-align: top; font-size: 1.3rem; font-family: Verdana, Geneva, Tahoma, sans-serif; vertical-align: top; color: #E5B464;" target="_blank">thejpchannel.com/</a></td>
    </tr>
    </tbody>
</table>

templates/basic/terminos_condiciones.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ include('global/header-user.html.twig') }}
    <section class="banner text-center d-flex justify-content-md-center pb-footer pt-header">
        <div class="border-brown-3 p-4 terminos-condiciones">
            <h2>{{ qi.texto('titulo_terminos_condiciones') }}</h2>
            <div>
                {{ qi.textoBig('terminos_condiciones')|raw }}
            </div>
        </div>

    </section>

{% endblock %}
{% block javascripts %}

{% endblock %}

templates/basic/videos.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <link href="https://vjs.zencdn.net/7.2.3/video-js.css" rel="stylesheet">
    {{ include('global/header-user.html.twig') }}
{#    <form action="{{ path('buscador') }}">#}
{#        <input id="query" name="query" />#}
{#    </form>#}

    <div class="container-fluid px-0 bg-blue min-vh-100  pb-footer bg-videos">
        <div class="preview_mob">
            <img src="{{ product_images~destacado.imagen }}" alt="">
            <a class="call-popUp bt-2" data-wallpaper="{{ product_images~destacado.imagen }}" data-video="{{ destacado.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ destacado.awsUrl }}" >
                Reproducir
            </a>
        </div>
        <div class="preview_web">
            {#Este deberia ser un tipo especial de video con:
             *texto enriquecido
             *2 espacios para links de vimeo
                Uno para el preview y otro para el video completo al que enlaza
             *
             #}
            <img class="wallpaper" src='{{ product_images~destacado.imagen }}'>
            {% if destacado.awsUrl %}
                <video muted="muted" width="640" height="270"  id="video_destacado" data-video="{{ qi.setting('bucket_s3') }}{{ destacado.awsPreviewUrl }}"></video>

            {% else %}
                <iframe src="https://player.vimeo.com/video/{{ destacado.idPreviewVimeo }}?color=09a6a7&title=0&byline=0&portrait&autoplay=1&controls=0"  frameborder="0" allow="autoplay"></iframe>
            {% endif %}
            <div class="textos">
                <img src="{{ product_images~destacado.categoria.imagen }}" alt="">
                <h2>{{ destacado.titulo }}</h2>
                <p>
                    {{ destacado.resumen }}
                </p>
                <a class="call-popUp pause-main bt-2" data-wallpaper="{{ product_images~destacado.imagen }}" data-video="{{ destacado.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ destacado.awsUrl }}">
                    Reproducir
                </a>
            </div>
        </div>
        {% for item in categorias %}
        <section class="categorias" id="cat{{ item.id }}">
            <div class="title">
{#                <img src="{{ item.imagen.ruta() }}"/>#}
                <h2>{{ item.nombre }}</h2>
            </div>
            <div class="s-g py-2 d-flex justify-content-between align-items-center">
                <div class="swiper-button-prev"></div>
                <div class="container-s-g">
                    <div class="swiper-wrapper">
                        {% for video in qi.videosCategoria(item.id) %}
                                <div class="swiper-slide">
                                    <a class="item call-popUp" data-wallpaper="{{ product_images~video.imagen }}" data-video="{{ video.idVimeo }}" data-domain="{{ qi.setting('bucket_s3') }}" data-aws="{{ video.awsUrl }}">
                                        <img class="w-100" src="{{ product_images~video.imagen }}"/>
                                        <span class="new">NEW!</span>
                                    </a>
                                </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="swiper-button-next"></div>
            </div>
        </section>
        {% endfor %}
    </div>


{% endblock %}
{% block javascripts %}
    <script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>
    <script>

        $(function () {
            var video = document.getElementById('video_destacado');
            var videoSrc = $('#video_destacado').data("video");
            if (Hls.isSupported()) {
                var hls = new Hls();
                hls.loadSource(videoSrc);
                hls.attachMedia(video);
                hls.on(Hls.Events.MANIFEST_PARSED, function() {
                    video.play();

                    console.log("play video");
                });
            }else if (video.canPlayType('application/vnd.apple.mpegurl')) {
                video.src = videoSrc;
                video.addEventListener('loadedmetadata', function() {
                    console.log("play video else if");
                    video.play();
                });
            }


            var players = []
            $('.preview_web').each(function() {

                    console.log('test1', players);

                    players.push({
                        player: new Vimeo.Player($(this).find("iframe").get(0)),
                        top: $(this).position().top,
                        status: "paused"
                    });
                    console.log('test2', players);

            });
            var viewportHeight = $(window).height();

            if( !$(".preview_web").is(":visible")) {
                for(var i=0; i<players.length;i++) {
                    players[i].status = "pause";
                    players[i].player["pause"]();
                }
            }
            $(window).on('scroll', function() {
                var scrollPos = $(window).scrollTop();
                for(var i=0; i<players.length;i++) {
                    var elementFromTop = players[i].top - scrollPos;
                    var status = (elementFromTop > 1000 && elementFromTop < players[i].top + viewportHeight + 500) ? "play" : "pause";
                    if(players[i].status != status) {

                        players[i].status = status;
                        players[i].player[status]();
                    }
                }
                video.stop();
            });
            $('.pause-main').click(function () {
                players[0].status = 'pause';
                $('.wallpaper').removeClass('hidden');

            });
            setTimeout(function(){
                $('.wallpaper').addClass('hidden');
            }, 1500);
        })
    </script>
{% endblock %}